<?php

/**
Implement HOOK_MENU
*/
function fullwidthtouchslider_menu() {
    $items['admin/structure/fullwidthtouchslider'] = array(
        'title' => t('Full Width Touch Slider'),
        'page callback' => 'fullwidthtouchslider_overview',
        'access arguments' => array('administer site configuration'),
        'description' => t('Full Page Slider')
    );
    $items['admin/structure/fullwidthtouchslider/add'] = array(
        'title' => t('Full Width Touch Slider'),
        'page callback' => 'drupal_get_form',
        'page arguments' => array('fullwidthtouchslider_form'),
        'access arguments' => array('administer site configuration'),
        'description' => t('Add Slides for Full page slider')
    );
    $items['admin/structure/fullwidthtouchslider/slide/delete/%'] = array(
        'title' => t('Are you sure want to delete slide'),
        'page callback' => 'drupal_get_form',
        'page arguments' => array('fullwidthtouchslider_delete_form'),
        'access arguments' => array('administer site configuration'),
        'description' => t('Delete slide for full slider')
    );
    $items['admin/structure/fullwidthtouchslider/slide/edit/%'] = array(
        'title' => t('Edit This Slide'),
        'page callback' => 'drupal_get_form',
        'page arguments' => array('fullwidthtouchslider_form'),
        'access arguments' => array('administer site configuration'),
        'description' => t('Edit slide for full slider')
    );    
    return $items;
}

/**
Implement HOOK_OVERVIEW
*/
function fullwidthtouchslider_overview() {
    try{
        $slides = db_query("SELECT * FROM {fullwidthtouchslider_data} ORDER BY id", array(), array('fetch' => PDO::FETCH_ASSOC));
        $header = array(t('heading'), t('Description'), t('Large Image'), t('Small Description'),
            array(
                'data' => t('Operations'),
                'colspan' => '2',
        ));
        $html = '';
        $html = l(t('add slides'), 'admin/structure/fullwidthtouchslider/add');
        $html .= '<h1>Slides</h1>';
        $rows = array();
        foreach ($slides as $slide) {
            $row = array(
                'heading' => $slide['heading'],
                'Description' => $slide['description'],
                'Large image' => "URL: ".file_create_url(file_load($slide['slide_fid'])->uri).' <br/ ><a href="'.file_create_url(file_load($slide['slide_fid'])->uri).'" target="blank">Click Here</a>',
                'Small Description' => $slide['image_fid'],
            );
            $row[] = array('data' => l(t('Edit'), 'admin/structure/fullwidthtouchslider/slide/edit/' . $slide['id']));
            $row[] = array('data' => l(t('Delete'), 'admin/structure/fullwidthtouchslider/slide/delete/' . $slide['id']));
            $rows[] = $row;
        }
        return $html . theme('table', array('header' => $header, 'rows' => $rows));
    } catch (Exception $ex) {
        return $ex->getMessage();
    }
}

/**
    Implement HOOK_FORM
    This form in for delting the slide
    hidden filed with slider id
*/
function fullwidthtouchslider_delete_form() {
    $form = array();
    $form['fullwidthtouchslider_markup'] = array(
        '#type' => 'markup',
        '#required' => TRUE,
        '#markup'   => t('Are you sure want to delete this slide'),
        '#weight' => 1
    );
    $form['fullwidthtouchslider_slidenumber'] = array(
        '#type' => 'textfield',
        '#value' => (arg(5))?arg(5):"",
        '#required' => TRUE,
        '#weight' => 2
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Delete'),
        '#weight' => 3
    );
    $form['cencle'] = array(
        '#type' => 'submit',
        '#value' => t('Cencle'),
        '#weight' => 4
    );
    return $form;
}

/**
 * Implement HOOK_FORM
 */

function get_edit_slide_information() {
    $id     =   arg(5);
    $slides =   db_select('fullwidthtouchslider_data','tbl')
                ->fields('tbl',array())
                ->condition('id',$id,'=')
                ->execute()->fetchAssoc();
    return $slides;
}
/**
    Implement HOOK_FORM_SUBMIT
    submit form for deleting the slide
*/
function fullwidthtouchslider_delete_form_submit($form , &$form_state) {
    try{
        $values         =   $form_state['values'];
        $op             =   $values['op'];
        $slide_number   =   $values['fullwidthtouchslider_slidenumber'];
        if(is_numeric($slide_number)) {
            if($op=='Cencle')   {
                drupal_goto('admin/structure/fullwidthtouchslider');
            } else {
                $query  =   db_query("DELETE from fullwidthtouchslider_data where id='$slide_number'");
                drupal_set_message('Slide has been deleted');
                drupal_goto('admin/structure/fullwidthtouchslider/slide');
            }
        }
    } catch (Exception $ex) {
        drupal_set_message($ex->getMessage());
    }
}

/**
    Implement HOOK_FORM
    this form is for uploading the slide for full width slider
*/

function fullwidthtouchslider_form() {
    $default_values =   array();
    if((arg(4)) && arg(4)=='edit') {
        $default_values =   get_edit_slide_information();
    }
    $form = array();
    $form['fullwidthtouchslider_headnig'] = array(
        '#type' => 'textfield',
        '#title' => 'Heading',
        '#required' => TRUE,
        '#default_value'    =>  ($default_values['heading'])?$default_values['heading']:"",
        '#weight' => 1
    );
    $form['fullwidthtouchslider_description'] = array(
        '#type' => 'textfield',
        '#title' => 'Description',
        '#required' => TRUE,
        '#default_value'    =>  ($default_values['heading'])?$default_values['heading']:"",
        '#weight' => 2
    );
    if(isset($default_values['slide_fid']) && $default_values['slide_fid']!=0) {
        $fid        =   $default_values['slide_fid'];
        $fileObj    =   file_load($fid);
        
        $form['fullwidthtouchslider'] = array(
            '#type' => 'fieldset',
            '#title' => t('Slide Image'),
            '#collapsible' => TRUE, // Added
            '#collapsed' => FALSE,  // Added
            '#weight'       => 3,
            '#prefix'       =>  '<div id="remove-file-callback-wrapper">',
            '#suffix'       =>  '</div>',
        );
        $form['fullwidthtouchslider']['fullwidthtouchslider_slide_image'] = array(
            '#type'         =>  'markup',
            '#title'        =>  t('Upload Sider large Image'),
            '#description'  =>  t("Sliderfull width image"),
            '#markup'       =>  '<img class="file-icon" alt="" title="image/png" src="/modules/file/icons/image-x-generic.png">'
                                . '<a target="blank" href="'.file_create_url($fileObj->uri).'">'.$fileObj->filename.'</a>'
                                .'<img src="'.file_create_url($fileObj->uri).'" width="300px" height="200px" class="img-responsive">',
            '#weight'       => 3
        );
        $form['fullwidthtouchslider']['fullwidthtouchslider_slide_id']    =   array(
            '#type' => 'hidden',
            '#default_value' => $default_values['id'],
            '#weight' => 5,
        );
        $form['fullwidthtouchslider']['fullwidthtouchslider_slide_image_remove']    =   array(
            '#type' => 'submit',
            '#value' => t('remove'),
            '#ajax' => array(
                'callback' => 'remove_file_callback',
                'wrapper' => 'remove-file-callback-wrapper',
              ),
            '#weight' => 5
        );
        
        $form['fullwidthtouchslider']['fullwidthtouchslider_slide_image_id'] = array(
            '#type' => 'textfield',
            '#value'=>  $fid,
            '#weight' => 3,
        );
    }else {
        $form['fullwidthtouchslider_slide_image'] = array(
            '#type' => 'managed_file',
            '#name' => 'fullwidthtouchslider_slide_image',
            '#title' => t('Upload Sider large Image'),
            '#description' => t("Sliderfull width image"),
            '#file_validate_extensions' => array(
                'png gif jpg jpeg'
            ),
            '#upload_location' => 'public://fullwidthslider_data/',
            '#weight' => 3
        );
    }
    $form['fullwidthtouchslider_textarea'] = array(
        '#type' => 'text_format',
        '#title' => t('Side Section'),
        '#description' => t("Side Section Content"),
        '#weight' => 4,
        '#default_value' => ($default_values['image_fid'])?$default_values['image_fid']:"",
    );
    if(empty($default_values)){
        $form['submit'] = array(
            '#type' => 'submit',
            '#value' => t('Add Slide'),
            '#weight' => 5
        );
    } else {
        $form['submit'] = array(
            '#type' => 'submit',
            '#value' => t('Update'),
            '#weight' => 5
        );
    }
    return $form;
}

/**
 * 
 */
function remove_file_callback($form,$form_state) {
    $fileId     =   $form_state['values']['fullwidthtouchslider_slide_image_id'];
    $slid       =   $form_state['values']['fullwidthtouchslider_slide_id'];
    if(file_load($fileId)) {
        file_delete(file_load($fileId));
    }
    $query      =   db_update('fullwidthtouchslider_data')
                    ->fields(array('slide_fid'=>0))
                    ->condition('id',$slid,'=')->execute();
    if ($query) {
            $ret =  '<script>';
            $ret .= 'jQuery(document).ready(function($) {';
            $ret .= '  location.reload(true);';
            $ret .= '});';
            $ret .= '</script>';
    }
    return $ret;
}
/**
    Implement HOOK_FORM_SUBMIT
    submit form for slide
*/
function fullwidthtouchslider_form_submit($form, &$form_state) {
    try{
        $data       = $form_state['values'];
        $heading    = $data['fullwidthtouchslider_headnig'];
        $desc       = $data['fullwidthtouchslider_description'];
        $fimg       = ($data['fullwidthtouchslider_slide_image'])?$data['fullwidthtouchslider_slide_image']:"";
        $stxt       = ($data['fullwidthtouchslider_textarea']['value'])?$data['fullwidthtouchslider_textarea']['value']:"";
        if(isset($fimg) && $fimg!="") {
            $file = file_load($fimg);
            $file->status = FILE_STATUS_PERMANENT;
            file_save($file);
        }
        $query = db_insert('fullwidthtouchslider_data')->fields(array(
                    'heading' => $heading,
                    'description' => $desc,
                    'slide_fid' => $fimg,
                    'image_fid' => $stxt
                ))->execute();
        drupal_set_message('Slide has been insterted successfully');
    } catch (Exception $ex) {
        drupal_set_message($ex->getMessage());
    }
}

/**
    Implement HOOK_BLOCK_INFO
*/
function fullwidthtouchslider_block_info() {
    $blocks['fullwidthtouchslider'] = array(
        'info' => t('full width touch slider'),
        'cache' => DRUPAL_NO_CACHE,
    );
    return $blocks;
}


/**
    Implement HOOK_BLOCK_VIEW
*/
function fullwidthtouchslider_block_view($delta = '') {
    $block = array();

    switch ($delta) {
        case 'fullwidthtouchslider':
            $block['subject'] = t('Full WidthSlider');
            $block['content'] = get_fullwidthtouchslider();
            break;
    }
    return $block;
}

/**
    Implement return function for block content
    @return theme
*/
function get_fullwidthtouchslider() {
    drupal_add_js(drupal_get_path('module', 'fullwidthtouchslider') . '/js/full-width-touch-slider.js');
    drupal_add_js(drupal_get_path('module', 'fullwidthtouchslider') . '/js/full-width-touch-slider.slider.js');
    drupal_add_js(drupal_get_path('module', 'fullwidthtouchslider') . '/js/full-width-touch-slider-custom.js');
    drupal_add_css(drupal_get_path('module', 'fullwidthtouchslider') . '/css/full-width-slider-style.css');
    $data = db_select('fullwidthtouchslider_data', 'fws')
                    ->fields('fws')->execute()->fetchAll();
    return theme('fullwidthslider', array('data' => $data));
}

/**
    Implement HOOK_THEME
*/
function fullwidthtouchslider_theme() {
    $themes = array(
        'fullwidthslider' => array(
            'template' => '/templates/homepageslider', // your template file called custompage.tpl.php
            'arguments' => array(),
        ),
    );
    return $themes;
}
